#!/bin/bash
# Automatically Update all Ports

rm -f /root/opensshport
rm -f /root/dropbearport
rm -f /root/stunnel4port
rm -f /root/openvpnport
rm -f /root/squidport

opensshport="$(netstat -nltp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nltp | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nltp | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nltp | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}' | cut -d: -f2 | xargs )"

echo $opensshport > /root/opensshport
cat > /root/opensshport <<-END
$opensshport
END

echo $dropbearport > /root/dropbearport
cat > /root/dropbearport <<-END
$dropbearport
END

echo $stunnel4port > /root/stunnel4port
cat > /root/stunnel4port <<-END
$stunnel4port
END

echo $openvpnport > /root/openvpnport
cat > /root/openvpnport <<-END
$openvpnport
END

echo $squidport > /root/squidport
cat > /root/squidport <<-END
$squidport
END
