#!/bin/bash
source /usr/local/sbin/base-script

clear
echo -e ""
echo -e "$TITLE"
echo -e " Membuat Akun Baru"
echo -e ""
read -p $'\e[32m  Username: \e[0m' User

# Check If Username Exist, Else Proceed
cat < /etc/passwd | cut -d: -f1 | grep -x -E "^${User}" >/dev/null
if [ $? -eq 0 ]; then
clear
echo -e ""
echo -e "$TITLE"
echo -e "\e[31m Username Already Exists on your server, please try another username\e[0m."
exit 0
else
read -p $'\e[32m  Password: \e[0m' Pass
read -p $'\e[32m  Active Days: \e[0m' Days
echo -e ""
echo -e ""
clear
sleep 1
IPADDR=$(wget -4qO- http://ipinfo.io/ip)
Today=`date +%s`
Days_Detailed=$(( $Days * 86400 ))
Expire_On=$(($Today + $Days_Detailed))
Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g' )"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2 | xargs | sed -e 's/ /, /g')"
squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}' | cut -d: -f2 | xargs )"
useradd -m -s /bin/false -e $Expiration $User > /dev/null
cat < /etc/passwd | cut -d: -f1 | grep -x -E "^${User}" &> /dev/null
echo -e "$Pass\n$Pass\n" | passwd $User &> /dev/null
clear
echo -e ""
echo -e "$TITLE"
echo -e ""
echo -e " Akun Premium VIP telah berhasil dibuat:"
echo -e ""
echo -e "\e[32m  Nama Pengguna : \e[0m"$User
echo -e ""
echo -e "\e[32m  Kata Sandi : \e[0m"$Pass
echo -e ""
echo -e "\e[32m  Masa Aktif Akun : \e[0m"$Expiration_Display
echo -e ""
echo -e "\e[32m  Host/IP : \e[0m"$IPADDR
echo -e ""
echo -e "\e[32m  OpenSSH Port : \e[0m"$opensshport
echo -e ""
echo -e "\e[32m  Dropbear Port : \e[0m"$dropbearport
echo -e ""
echo -e "\e[32m  SSL Port : \e[0m"$stunnel4port
echo -e ""
echo -e "\e[32m  Proxy Ports : \e[0m"$squidport
echo -e ""
echo -e "\e[32m  OpenVPN Port : \e[0m"$openvpnport
echo -e ""
echo -e ""
echo -e ""
fi