#!/bin/bash
# Script by : _Dreyannz_
rm -f /root/opensshport
rm -f /root/dropbearport
rm -f /root/stunnel4port
rm -f /root/openvpnport
rm -f /root/squidport
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(cat /etc/privoxy/config | grep -i listen-address | awk '{print $2}' | cut -d: -f2 | xargs )"
echo $opensshport > /root/opensshport
cat > /root/opensshport <<-END
$opensshport
END
echo $dropbearport > /root/dropbearport
cat > /root/dropbearport <<-END
$dropbearport
END
echo $stunnel4port > /root/stunnel4port
cat > /root/stunnel4port <<-END
$stunnel4port
END
echo $openvpnport > /root/openvpnport
cat > /root/openvpnport <<-END
$openvpnport
END
echo $squidport > /root/squidport
cat > /root/squidport <<-END
$squidport
END

cd
clear
echo -e ""
echo -e " == BonvScript == " | lolcat -a
echo -e ""
echo -e " Stunnel4 Port: $stunnel4port"
echo -e ""
read -p " Which Port Should Be Changed?: " Port
egrep "^$Port" /root/stunnel4port >/dev/null
if [ $? -eq 0 ]; then
	read -p " From Port $Port -> Port?: " Port_New
	if grep -Fxq $Port_New /root/opensshport; then
		echo -e ""
		echo -e " OpenSSH Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	if grep -Fxq $Port_New /root/dropbearport; then
		echo -e ""
		echo -e " Dropbear Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	if grep -Fxq $Port_New /root/openvpnport; then
		echo -e ""
		echo -e " Openvpn Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	if grep -Fxq $Port_New /root/squidport; then
		echo -e ""
		echo -e " Squid3 Port Conflict"
		echo -e " Port Is Already In Use"
		echo -e ""
		exit
	fi
	Port_Change="s/$Port/$Port_New/g";
	sed -i $Port_Change /etc/stunnel/stunnel.conf
	service stunnel4 restart > /dev/null
	rm -f /root/stunnel4port
	stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
	clear
	echo -e ""
echo -e " == BonvScript == " | lolcat -a
	echo -e " Stunnel4 Port: $stunnel4port"
	echo -e ""

else
	clear
	echo -e ""
	echo -e " Port you entered does not"
	echo -e " exists in stunnel config"
	echo -e " exiting...."
  echo -e ""
fi
