#!/bin/bash

clear
echo -e ""
echo -e " == FlaSSH == " | lolcat -a
echo -e ""
echo -e "   [1] Reboot Sekarang"
echo -e ""
echo -e "   [2] Jadwalkan Reboot"
echo -e ""
echo -e "   [3] Keluar"
echo -e ""
read -p "   Tentukan Pilihanmu [1-3]: " Reboot
echo -e ""
sleep 3
clear
case $Reboot in
		1)
		clear
		reboot
		exit
		;;
		2)
		clear
		reboot_sys_auto
		exit
		;;
		3)
		clear
		exit
		;;
	esac