#!/bin/bash

clear
echo -e ""
echo -e " == FlaSSH == " | lolcat -a
echo -e ""
read -p " Nama Pengguna: " User
echo -e ""
sleep 2
egrep "^$User" /etc/passwd &> /dev/null
if [ $? -eq 0 ]; then
	userdel -f $User
  rm -rf /home/$User
	clear
	echo -e ""
  echo -e " == FlaSSH == " | lolcat -a
  echo -e ""
	echo -e " Akun Sudah Dihapus"
	echo -e ""
else
	clear
	echo -e ""
  echo -e " == FlaSSH == " | lolcat -a
  echo -e ""
	echo -e " Akun yang kamu input tidak terdaftar"
	echo -e ""
fi