#!/bin/bash

Username=`cat /etc/passwd | grep -Ew ^$1 | cut -d":" -f1`
if [ "$Username" = "" ]
then
	clear
	echo -e ""
  echo -e " == FlaSSH == " | lolcat -a
  echo -e ""
	echo -e " Nama Pengguna Tidak Ditemukan"
	echo -e ""
	exit
fi
Userid=`cat /etc/passwd | grep -Ew ^$Username | cut -d":" -f3`
UserPrimaryGroupId=`cat /etc/passwd | grep -Ew ^$Username | cut -d":" -f4`
UserPrimaryGroup=`cat /etc/group | grep :"$UserPrimaryGroupId": | cut -d":" -f1`
UserInfo=`cat /etc/passwd | grep -Ew ^$Username | cut -d":" -f5`
UserHomeDir=`cat /etc/passwd | grep -Ew ^$Username | cut -d":" -f6`
UserShell=`cat /etc/passwd | grep -Ew ^$Username | cut -d":" -f7`
UserGroups=`groups $Username | awk -F": " '{print $2}'`
PasswordExpiryDate=`chage -l $Username | grep "Password expires" | awk -F": " '{print $2}'`
LastPasswordChangeDate=`chage -l $Username | grep "Last password change" | awk -F": " '{print $2}'`
AccountExpiryDate=`chage -l $Username | grep "Account expires" | awk -F": " '{print $2}'`
HomeDirSize=`du -hs $UserHomeDir | awk '{print $1}'`
clear
echo -e ""
echo -e " == FlaSSH == " | lolcat -a
echo -e ""
echo -e "  Informasi Member: "
echo -e ""
echo -e " Nama Pengguna: $Username"
echo -e ""
echo -e " Perubahan kata sandi sebelumnya: $LastPasswordChangeDate"
echo -e ""
echo -e " Tanggal Expired: $AccountExpiryDate"
echo -e ""
